### ISSUE TITLE
깃허브 페이지로도 올려줘요!

### ISSUE THREAD

**Issue by plantstoen** [cokia/dimi-tranding-repo#1]
뭐 당연히 잘 하시겠지만... Vue프로젝트를 이렇게 올릴수있더라구요 :)
https://medium.com/@Roli_Dori/deploy-vue-cli-3-project-to-github-pages-ebeda0705fbd

바로 볼수있으면 좋을듯..!

**Comment by cokia** [comment]
헉..! 몰랐는데 뷰 프로젝트도 바로 깃허브페이지로 올릴수있네요..!!
바로 올려두겠습니다! 감사합니다..! (찡긋)
